### ISSUE TITLE
Uncaught Error with session replay

### ISSUE THREAD

**Issue by rahulkgupta** [PostHog/posthog-js#1229]
```
sessionrecording.ts:789 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'd'
    |     property 'components' -> object with constructor 'Object'
    |     property 'position' -> object with constructor 'n'
    --- property 'el' closes the circle
    at JSON.stringify (<anonymous>)
    at e.value (sessionrecording.ts:789:27)
    at emit (sessionrecording.ts:683:22)
    at ht (index.js:108:57)
    at le (index.js:138:9)
    at He.e.mutationCb (observer.js:731:19)
    at e.emit (mutation.js:308:18)
    at e.processMutations (mutation.js:107:18)
```

I think it's happening with const size = JSON.stringify(event).length when trying to record events from aframe framework (https://aframe.io/)

**Comment by rahulkgupta** [comment]
more info for recreating in https://github.com/3DStreet/3dstreet/pull/601
