### ISSUE TITLE
RangeError: Maximum call stack size exceeded (Next.js App Dir)

### ISSUE THREAD

**Issue by oagix** [PostHog/posthog-js#1303]
Using PostHog JS (React) with a Next.js (app dir) turbopack app. The `posthog.capture` function (as well as other internal ones like autocapture) trigger a maximum stack depth size exceeded error.

This seems to have been a bug for a very long time but it's uncaught. Sentry's billing is absolutely in pain when that error fires endlessly. How can we debug and prevent this?

![Screenshot 2024-07-12 at 8 58 55 PM](https://github.com/user-attachments/assets/461854b9-1e10-44f2-92e2-4e9eb7fea9e7)

**Comment by pauldambra** [comment]
Hey @oalexdoda 

copying your question from the other issue you posted it

> How can we add data-turbo-eval="false" while using the Next.js / React SDK? Not sure if related but this is happening on Next.js app dir turbopack. Absolutely destroys our Sentry events billing.

There'a a chance you can't but honestly it's a question for turbopack not for posthog

Turbopack is pretty clever - but it's cleverness means that it simply won't always work with all third party libraries.

I _think_ that the only way to use turbopack with posthog (and other libraries too) is to include the snippet and mark it `data-turbo-eval="false"` 

My understanding of turbopack is that this is a trade-off of using it. Some things will be faster with the trade-off some things will need work arounds. 

I guess that's maybe a frustrating answer but you all know turbopack better than us so if there is a solution it's way more likely to come from turbopack or the turbopack community than from us.

**Comment by pauldambra** [comment]
closing since this isn't something we can fix in PostHog (I think)

happy to hear solutions from others if we're missing a trick...

**Comment by lincolnremi** [comment]
Is there a mixup here between Next.js turbopack and the Rails hotwired/turbo library? I'm not aware of any `data-turbo-eval` attribute that Next.js turbopack uses.

**Comment by pauldambra** [comment]
Ah, damn, sorry - pattern matching :)

in which case some public example or repro would be super helpful!

**Comment by pauldambra** [comment]
(have edited this misleading link out of the issue description)

**Comment by neoromantic** [comment]
Stumbled on this too. 

```
module.js:1 [PostHog.js] [SessionRecording] could not emit queued rrweb event. RangeError: Maximum call stack size exceeded
...
```

Happens after numerous route changes on Next 15@canary with app router.

**Comment by neoromantic** [comment]
Happens sporadically, when i transition between pages. 

For now, i couldn't identify the reason, but it happens only after 10-15 route changes. 

Not every time, but pretty reproducible. 

No idea how to debug...

**Comment by pauldambra** [comment]
> Not every time, but pretty reproducible.

Is it possible you could create the reproduction @neoromantic - the ecosystem is pretty large and i could end up chasing shadows 🙈 

What's interesting in the error you share is the 'rrweb queueing' is only intended as a stopgap. It's there because sometimes recording takes slightly longer to start and we try to poke custom events in before its ready. So it points at some other thing causing a problem with that message as a symptom

**Comment by lukebelbina** [comment]
I am seeing this on our nextjs site, no idea how to debug.

![image](https://github.com/user-attachments/assets/9a7a2d6d-03df-4809-82e3-a5efeabe9576)

**Comment by Raj1v** [comment]
Facing the same issue on our Vue.js setup. Same stack trace as shown by @lukebelbina 
Currently, the issue only appears in our staging environment.

**Comment by Raj1v** [comment]
@pauldambra 
Yes, the error seems to originate from the `_execute_array` function. In my understanding, this function sends over events triggered before Posthog got initialized.

I placed a breakpoint in the function (line 687 in screenshot), which is indeed hit many times before the call stack gets exceeded.
The breakpoint on line 689 is never hit.

![Screenshot 2024-10-15 at 10 21 49 AM](https://github.com/user-attachments/assets/4fc423ea-fb46-41f6-874b-4c7472af3578)

**Comment by pauldambra** [comment]
Oh fascinating! That code has been there since day 0 🤯 

It looks like the array is a single item so my gut feel is that it's not the content of the array. Can you share your snippet?

**Comment by Raj1v** [comment]
```js
import posthog from 'posthog-js'

export default {
	install(app) {
		/**
		 * @type {import('posthog-js').PostHog}
		 */
		const instance = app.config.globalProperties.$posthog = posthog.init(import.meta.env.VITE_POSTHOGKEY, {
			api_host: 'XXXX', // Reverse proxy hosted on Azure Front Door
			ui_host: 'https://eu.posthog.com',
			capture_pageview: false,
			person_profiles: 'identified_only', 
		})
		app.provide('posthog', instance)
		app.config.globalProperties.$posthog = instance;
		window.posthog = instance
	},
}

```

Using the Vue JS plugin setup [from the docs](https://posthog.com/docs/libraries/vue-js#method-1-create-a-plugin).

Stopping to emit the `$pageview` event on route changes stops the errors.

**Comment by Raj1v** [comment]
Browser also seems to affect the issue. On Safari, the error triggers consistently on each page load. On Chome only occasionally .

**Comment by pauldambra** [comment]
But not in your production build?

**Comment by Raj1v** [comment]
Turns out it was an accidental double initialization from the JS SDK. Once through Google Tag Manager, and once through Vue.

**Comment by oalexdoda** [comment]
Maybe all it needs is a throttle on the session recordings side and to check if an instance already exists before re-initializing it.

**Comment by crcorbett** [comment]
Also experiencing this issue!

`posthog-js: v1.214.0`
`next:15.1.0`

The error appears after rapid route changes caused, in our case caused by search params updating when tanstack table filters / pagination controls are updated. Setting `disable_session_recording=true` resolves the issue.

<img width="858" alt="Image" src="https://github.com/user-attachments/assets/36c05a71-aaa5-46ad-92f2-4b81ae407515" />

**Comment by yonitou** [comment]
So can we have an answer on this issue ? I'm experiencing the exact same thing (with a simple Vite React App)

**Comment by typeofweb** [comment]
Just received `Maximum call stack size exceeded` in Next.js App Dir. Sentry reported over 1600 events!

I'm happy to share my stack trace:

<details>
<summary><b>RangeError: Maximum call stack size exceeded</b></summary>
<pre>
  at console.overrideMethod(app:///build/installHook.js:1:146977)
  at <anonymous>(./node_modules/.pnpm/@sentry+core@9.6.0/node_modules/@sentry/core/build/esm/utils-hoist/instrument/console.js:36:1)
  at t._log(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:1752)
  at t.warn(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:1960)
  at iq._tryRRWebMethod(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58871)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._pageViewFallBack(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:64033)
  at iq.onRRwebEmit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:61962)
  at this.stopRrwebemit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:60599)
  at At(app:///static/recorder.js:1:74046)
  at Wt.addCustomEvent(app:///static/recorder.js:1:79813)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._tryRRWebMethod(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58685)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._pageViewFallBack(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:64033)
  at iq.onRRwebEmit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:61962)
  at this.stopRrwebemit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:60599)
  at At(app:///static/recorder.js:1:74046)
  at Wt.addCustomEvent(app:///static/recorder.js:1:79813)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._tryRRWebMethod(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58685)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._pageViewFallBack(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:64033)
  at iq.onRRwebEmit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:61962)
  at this.stopRrwebemit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:60599)
  at At(app:///static/recorder.js:1:74046)
  at Wt.addCustomEvent(app:///static/recorder.js:1:79813)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._tryRRWebMethod(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58685)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._pageViewFallBack(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:64033)
  at iq.onRRwebEmit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:61962)
  at this.stopRrwebemit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:60599)
  at At(app:///static/recorder.js:1:74046)
  at Wt.addCustomEvent(app:///static/recorder.js:1:79813)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._tryRRWebMethod(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58685)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._pageViewFallBack(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:64033)
  at iq.onRRwebEmit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:61962)
  at this.stopRrwebemit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:60599)
  at At(app:///static/recorder.js:1:74046)
  at Wt.addCustomEvent(app:///static/recorder.js:1:79813)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._tryRRWebMethod(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58685)
  at iq._tryAddCustomEvent(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:58951)
  at iq._pageViewFallBack(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:64033)
  at iq.onRRwebEmit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:61962)
  at this.stopRrwebemit(./node_modules/.pnpm/posthog-js@1.231.1_@rrweb+types@2.0.0-alpha.17/node_modules/posthog-js/dist/module.js:1:60599)
  at At(app:///static/recorder.js:1:74046)
</pre>
</details>

```
Relevant Packages:
  next: 15.3.0-canary.18 // Latest available version is detected (15.3.0-canary.18).
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.8.2
  posthog-js: 1.232.3
  posthog-node: 4.10.1
```

**Comment by Chhinna** [comment]
Would love to have a fix for this, not the error you want to run into on a friday night.

**Comment by velevtzvetlin** [comment]
What is the status of this issue?

**Comment by martinstepanek** [comment]
Also having issue mentioned above "[PostHog.js] [SessionRecording] could not emit queued rrweb event. RangeError: Maximum call stack size exceeded"

**Comment by mohamedary** [comment]
I'm also experiencing the same issue.

**Comment by pauldambra** [comment]
I appreciate people adding that they're experiencing something,,, but we don't know what the issue is and it doesn't occur for everyone 

so we really need more info on your site, your posthog setup, or what is happening when it triggers for you

**Comment by raxosiris** [comment]
@pauldambra you can try our live site: https://gamescript.ai where this error regularly occurs. Hopefully inspecting the index file source you'll be able to see our calls. We are using the recommended web snippet.

Our setup is:
Axum, Dioxus (wasm)

But from the browser perspective (where this script executes) it's just html/css/js/wasm.

**Comment by pauldambra** [comment]
Hey @raxosiris 

<img width="553" alt="Image" src="https://github.com/user-attachments/assets/cc5e8946-4754-407a-915d-e1864fc548cc" />

you're including posthog more than once, you need to include posthog only once or you will get this error

**Comment by elektronik2k5** [comment]
@pauldambra although it is definitely reasonable to expect Posthog users to only ever include the script once on a page, it is also reasonable and easy to detect this case and avoid any runtime errors. You can log a warning to the browser console, as well as the online customer dashboard instead.

In fact, as a user of Posthog, that's exactly what I'd expect to happen.

**Comment by Deathslayer89** [comment]
getting same error RangeError: Maximum call stack size exceeded , i have used posthog wizard to setup .

**Comment by elektronik2k5** [comment]
@pauldambra I'd like to repeat my message from above: although the script shouldn't be included more than once on the page, telling your customers to fix that instead of adding a trivial change to your code which would solve this once and for all categorically is really not the way to gain user satisfaction for your product.

I mean, just add this to the top of your entry point script: 
```js
if (globalThis.didLoadPostHog) {
  return
}

globalThis.didLoadPostHog = true

// That's it - the rest of the script goes here. Problem solved. Done.
```

And then it won't matter how many times posthog is added to the page cause it will run exactly once. This is pretty standard practice for all 3rd party integration scripts and honestly should have been there from day 1.

Also, you can compare how posthog fairs in this test to all other 3rd party scripts and see whether they throw errors and then instruct their users to go fix the integration - or do they just take care of it themselves.

**Comment by pauldambra** [comment]
hey @elektronik2k5 

thanks for the advice. you might even be right! PRs are welcome.

honestly, the overhead here isn't opening the PR. It would be testing that this actually resolves the problem. checking the other open source implementations to see what they've learned in solving  this, making sure it really is the fix, and doesn't break anything else. 

So, it's not that I disagree with you but that there's always more work to do then can be done in any one day.

_Also_ the fact that folk are reporting different errors down the thread means I don't know that there's only one bug here so I don't want to ship something - which is all bytes that have to be downloaded and lines of code to be maintained - and not know that it resolves the issue

**Comment by Deathslayer89** [comment]
@pauldambra i have checked the code, posthog is being used only once in the root app layout

**Comment by yohanc3** [comment]
> [@Deathslayer89](https://github.com/Deathslayer89) it's not whether your code has it once, but if it ends up in the HTML twice. It's very difficult to debug things in short github messages.
> 
> i'm currently testing a new feature using an example nextjs app and don't get this - and many other people are using next and posthog together - so it's not as simple as "using in a nextjs app"
> 
> we really need as much info as you can share - ideally a minimal reproducible example repo we can look at

@pauldambra are you loading lots of data on multiple pages? I'm currently experiencing the same issue, but it only happens in non-production environments, as @Raj1v mentioned before. 

For me, and similarly to other people in the thread, the issue occurs when loading 30-100 rows from a db on page, and navigating among several pages almost continuously.

**Comment by pauldambra** [comment]
@yohanc3 it would be amazing if you have time to set up a minimal reproducible example

that it happens in non-prod environments sounds like a hot reload issue, but there are so many different ways to setup a dev environment that i could very easily fix it for me and not fix it for you

so many folk have chimed in slightly differently that i'm not convinced this is only one issue, yet 😅

**Comment by alexander-gladshev** [comment]
Добрый день. У меня такая-же проблема. Ошибка "RangeError: Maximum call stack size exceeded". Я исключил повторную инициализацию posthog как предлагалось выше в этом треде. Но у меня ошибка все еще присуцтвует. Прилагаю скриншоты для. более полной картины.

<img width="504" height="236" alt="Image" src="https://github.com/user-attachments/assets/4929c90f-3486-42db-b3be-61ccc3938d83" />
<img width="925" height="934" alt="Image" src="https://github.com/user-attachments/assets/ef1c1091-7e60-41e7-b8f0-56e9ede65836" />
<img width="971" height="124" alt="Image" src="https://github.com/user-attachments/assets/8547ffe7-998e-4ac6-a185-78738629ab39" />
<img width="969" height="98" alt="Image" src="https://github.com/user-attachments/assets/4b82263a-ee40-45ce-9cd8-db519e2e834d" />
<img width="746" height="107" alt="Image" src="https://github.com/user-attachments/assets/edf69cea-88cc-46f3-929d-f9bb87ed4ea6" />
<img width="565" height="135" alt="Image" src="https://github.com/user-attachments/assets/68ade81d-5b67-401a-b21c-525764c8b5bb" />
<img width="589" height="860" alt="Image" src="https://github.com/user-attachments/assets/e737eac7-6f2c-4b4a-a861-091127118ab7" />

**Comment by lucasheriques** [comment]
hey folks, I'm trying to come up with a solution for this, but if anyone can share an minimum reproducible example that would help a lot

@alexander-gladshev I see you are using both the JS snippet in the DOM, and you're also calling posthog.init in your code? or am I misunderstanding?

**Comment by marandaneto** [comment]
i think this is fixed already, pls report back otherwise
