### ISSUE TITLE
Popover surveys not showing up when serving bundled posthog with disable_external_dependency_loading set to true

### ISSUE THREAD

**Issue by vonBrax** [PostHog/posthog-js#1377]
## Bug description

When using the JavaScript Web SDK and bundling the posthog dependencies as described in the [docs](https://posthog.com/docs/libraries/js#advanced-option---bundle-all-required-extensions), the popover surveys are not showing up when they should.

The survey is correctly configured in Posthog without any display conditions, and it was also never dismissed by the user (or shown).

As far as I could debug this issue, the problem seems to be that the line https://github.com/PostHog/posthog-js/blob/0b40e5af5381c7d356de31fc0458e91afbfa9a6b/src/posthog-surveys.ts#L82 is never executed because of the check for the `surveysGenerator` on line https://github.com/PostHog/posthog-js/blob/0b40e5af5381c7d356de31fc0458e91afbfa9a6b/src/posthog-surveys.ts#L73, which is set here https://github.com/PostHog/posthog-js/blob/864169ca3f862b57819f26af2aacf8c0a67ee928/src/entrypoints/surveys.ts#L9 and executed when the bundled file is loaded in the browser.

I could workaround the issue by patching the `surveys.instance._surveyManager` variable with:

```javascript
posthog.surveys._surveyManager =  window.extendPostHogWithSurveys(posthog.surveys.instance);
```

After the above line is executed, the survey popover immediatelly shows up.

*If this affects the front-end, screenshots would be of great help.*  

 -- 

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

 -- 

## How to reproduce

1. Create popover survey and launch it
2. Create an frontend application using the bundled posthog as described in the [docs](https://posthog.com/docs/libraries/js#advanced-option---bundle-all-required-extensions). 
3. Call `posthog.init` passing `true` to `disable_external_dependency_loading` 

## Environment

- [ ] PostHog Cloud US, project ID: [please provide from https://us.posthog.com/settings/project-details#variables]
- [X] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

## Additional context
We are using posthog in our frontend application built using [Nuxt](https://nuxt.com/)

**Comment by phillipmohr** [comment]
I'm having the same problem in Nuxt 3. Could you please tell me where I would need to put this line? `posthog.surveys._surveyManager =  window.extendPostHogWithSurveys(posthog.surveys.instance);` @adamplenti @vonBrax

**Comment by vonBrax** [comment]
@phillipmohr 

I'm not sure how you're project is structured. We are using a custom posthog plugin, not the posthog nuxt module.
In our case, we are performing the surveys workaround in the posthog loaded callback:

```typescript
posthogInstance.value = posthog.init(phToken.value, {
  ...
  loaded: (phClient) => {
    ...
    handleSurveysWorkaround(phClient);
    ...
  },
  ...
});

/**
 * Tempory workaround to make the posthog surveys work. This function should be
 * removed once the issue is fixed on the posthog side.
 *
 * @see https://github.com/PostHog/posthog-js/issues/1377
 *
 * @param phClient - the posthog client instance
 */
function handleSurveysWorkaround(phClient: PostHog) {
  const posthogSurveys = phClient.surveys;

  // @ts-expect-error Property '_surveyManager' is private and only accessible within class 'PostHogSurveys'
  posthogSurveys._surveyManager = window.extendPostHogWithSurveys(
    // @ts-expect-error Property 'instance' is private and only accessible within class 'PostHogSurveys'
    posthogSurveys.instance,
  );
}
```

**Comment by phillipmohr** [comment]
Thank you very much for the detailed answer @vonBrax 

I'm using the official approach by PostHog for Nuxt 3 mentioned here: https://posthog.com/docs/libraries/nuxt-js 

I've implemented your solution in my `posthog.client.js` but unfortunately I'm getting the error: 
```
posthog.client.js:6 [PostHog.js] `loaded` function failed TypeError: window.extendPostHogWithSurveys is not a function
    at handleSurveysWorkaround (posthog.client.js:18:44)
    at Object.loaded (posthog.client.js:10:7)
    at _Ro._loaded (posthog-core.ts:626:25)
    at _Ro._init (posthog-core.ts:577:18)
    at _Ro.init (posthog-core.ts:380:25)
    at posthog.client.js:6:33
```

This is my `posthog.client.js`: 


```js
import { defineNuxtPlugin } from '#app'
import posthog from 'posthog-js'

export default defineNuxtPlugin(nuxtApp => {
  const runtimeConfig = useRuntimeConfig();
  const posthogClient = posthog.init(runtimeConfig.public.posthogPublicKey, {
    api_host: runtimeConfig.public.posthogHost || 'https://eu.i.posthog.com',
    capture_pageview: false, // we add manual pageview capturing below
    loaded: (posthogClient) => {
      handleSurveysWorkaround(posthogClient);
    }
  })

  function handleSurveysWorkaround(phClient) {
    const posthogSurveys = phClient.surveys;

    // @ts-expect-error Property '_surveyManager' is private and only accessible within class 'PostHogSurveys'
    posthogSurveys._surveyManager = window.extendPostHogWithSurveys(
      // @ts-expect-error Property 'instance' is private and only accessible within class 'PostHogSurveys'
      posthogSurveys.instance,
    );
  }

  // Make sure that pageviews are captured with each route change
  const router = useRouter();
  router.afterEach((to) => {
    nextTick(() => {
      posthog.capture('$pageview', {
        current_url: to.fullPath
      });
    });
  });

  return {
    provide: {
      posthog: () => posthogClient
    }
  }
})

```

If I should find a solution, I'll update it here

**Comment by vonBrax** [comment]
@phillipmohr 

I'm not 100% sure about this, but I would assume that `extendPostHogWithSurveys` is only set when you're manually bundling posthog, as I wrote in the description. I tried to find the documentation for that, but seems like they removed it, so not sure if that option is still officially supported.

Basically the idea was to create a file where you would import the relevant posthog modules and generate a bundle out of that file. In our case, we would have an `import 'posthog-js/dist/surveys';` in that file. If I'm not mistaken, this is where the `extendPostHogWithSurveys` function would be globally set.

If you're not manually bundling the posthog modules, then you probably have a different problem than the one described in this issue.

Another possibility that I can think of is that you could be calling the `handleSurveysWorkaround` function inside the SSR context?

**Comment by gautamsarawagi** [comment]
@vonBrax can you please help me with this issue. I am also experincing the same issue. The surveys are not showing in the UI and the major reason I guess is `/static/survey.js` endpoint may be blocked as I cannot see this being loaded in the network request. 

Here is the Provider I am using: 

```
<PostHogProvider
      apiKey={process.env.REACT_APP_POSTHOG_KEY}
      options={{
        api_host: process.env.REACT_APP_POSTHOG_API_HOST,
        ui_host: process.env.REACT_APP_POSTHOG_UI_HOST,
        disable_session_recording: true,
        capture_pageview: false,
        capture_pageleave: false,
        session_recording: {
          maskAllInputs: false,
          maskInputOptions: {
            password: true,
          },
        },
      }}
    >
      <HelmetProvider>
        <Toaster position="top-center" />
        <App />
      </HelmetProvider>
    </PostHogProvider>
```

**Comment by marandaneto** [comment]
Since the latest versions, this code has changed a bit and might have solved itself already.
Can you try reproducing it using the latest version and see if it's still an issue?

**Comment by vonBrax** [comment]
Hey @marandaneto , I'll check here if it's works now with the latest version and without the workaround.
I'll report back here as soon as I have an answer.

**Comment by marandaneto** [comment]
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by marandaneto** [comment]
> Hey [@marandaneto](https://github.com/marandaneto) , I'll check here if it's works now with the latest version and without the workaround. I'll report back here as soon as I have an answer.

thanks, closing it for now but as I mentioned [here](https://github.com/PostHog/posthog-js/issues/1377#issuecomment-2788838552), I can reopen if its still an issue.
