### ISSUE TITLE
Invalid hooks call on NextJS

### ISSUE THREAD

**Issue by davidlky** [PostHog/posthog-js#1427]
Hi, im using posthog with NextJS 14

```
    "posthog-js": "^1.163.0",
...
    "next": "^14.2.13",
```

and Im getting 
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ⨯ Internal error: TypeError: Cannot read properties of null (reading 'useMemo')
    at Object.useMemo (/Users/david/Documents/vouch/node_modules/react/cjs/react.development.js:1650:21)
    at PostHogProvider (/Users/david/Documents/vouch/node_modules/posthog-js/react/dist/umd/index.js:16:29)
```

my providers looks like this, and if i remove the PosthogProvider, it works just fine...

```
"use client";

import type { PostHog } from "posthog-js";
import React, { useEffect, useState } from "react";
import { usePathname, useSearchParams } from "next/navigation";
import { env } from "@/env.mjs";
import { type Session } from "next-auth";
import posthog from "posthog-js";
import { PostHogProvider } from "posthog-js/react";


const PostHogPageview = ({ posthogClient }: { posthogClient?: PostHog }) => {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  // Track pageviews
  useEffect(() => {
    if (pathname) {
      let url = window.origin + pathname;
      if (searchParams?.toString()) {
        url = url + `?${searchParams?.toString()}`;
      }
      if (posthogClient?.__loaded)
        posthogClient?.capture("$pageview", {
          $current_url: url,
          $pathname: pathname,
        });
    }
  }, [pathname, searchParams, posthogClient]);

  return <></>;
};

export function Providers(props: {
  children: React.ReactNode;
  serverSession?: Session | null;
  language: SupportedLanguage;
}) {
  const [postHogClient, setPostHogClient] = useState<PostHog | undefined>();

  useEffect(() => {
    if (postHogClient) {
      return;
    }
    if (
      typeof window !== "undefined" &&
      env.NEXT_PUBLIC_POSTHOG_KEY &&
      env.NEXT_PUBLIC_POSTHOG_HOST
    ) {
      posthog.init(env.NEXT_PUBLIC_POSTHOG_KEY, {
        api_host: env.NEXT_PUBLIC_POSTHOG_HOST,
        persistence: "localStorage+cookie",
      });
    }

    setPostHogClient(posthog);
  }, [postHogClient]);

  useEffect(() => {
    if (postHogClient?.__loaded)
      postHogClient.identify(props.serverSession?.user?.id, {
        email: props.serverSession?.user.email,
        intercomId: props.serverSession?.user.intercomId,
        name: props.serverSession?.user.firstName + " " + props.serverSession?.user.lastName,
      });
    postHogClient?.setPersonPropertiesForFlags({ email: props.serverSession?.user.email });
  }, [props.serverSession?.user, postHogClient]);
  return (
              <PostHogProvider client={posthog}>
                <main>{props.children}</main>
                <PostHogPageview posthogClient={posthog} />
              </PostHogProvider>
  );
}
```

**Comment by davidlky** [comment]
Nevermind, this is due to my `serverComponentsExternalPackages` in my nextjs config
