### ISSUE TITLE
t.at is not a function. (In 't.at(-1)', 't.at' is undefined)

### ISSUE THREAD

**Issue by aleksandr-shevchenko-0** [PostHog/posthog-js#1518]
Hello!
We are using posthog-js. 
Started catching the error:

```console
TypeError: t.at is not a function. (In 't.at(-1)', 't.at' is undefined)
  at ? (webpack://@fundraiseup/dashboard/../../node_modules/posthog-js/dist/module.js:1:36824)
  at stringify([native code])
  at wn(webpack://@fundraiseup/dashboard/../../node_modules/posthog-js/dist/module.js:1:36764)
  at onRRwebEmit(webpack://@fundraiseup/dashboard/../../node_modules/posthog-js/dist/module.js:1:62930)
  at headMetaVerification(webpack://@fundraiseup/dashboard/../../node_modules/posthog-js/dist/module.js:1:60800)
  at node(../node_modules/.pnpm/rrweb@2.0.0-alpha.16_patch_hash=x52pllmg6k5suqkcoa7bdybazq/node_modules/rrweb/dist/rrweb.js:1:1)
  at apply(../node_modules/.pnpm/rrweb@2.0.0-alpha.16_patch_hash=x52pllmg6k5suqkcoa7bdybazq/node_modules/rrweb/dist/rrweb.js:1:1)
  at i(webpack://@fundraiseup/dashboard/../../node_modules/@sentry/browser/esm/helpers.js:90:17)
```

<img width="846" alt="image" src="https://github.com/user-attachments/assets/56408d8e-baf1-47e1-9d00-e2ad761e4fe9">

Is it a bug? Which browser versions are supported by posthog-js?

**Comment by aleksandr-shevchenko-0** [comment]
Hey, @pauldambra!
Thanks for your answer!

We've updated to the latest version, but since we can't reproduce the bug ourselves, we'll follow the results in Sentry.

I will report on the result

**Comment by andrei-zanouski** [comment]
Hello, @pauldambra!
We continue to catch errors 
poshog-js version is `^1.184.1`

```
e.at is not a function. (In 'e.at(-1)', 'e.at' is undefined)
```
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/1851c8d8-c93b-4416-97de-ced1897bb797">

I found `.at` in your code only in one place 
https://github.com/PostHog/posthog-js/blob/d71ecd6b5dd69c8f19fb7c957c55a6888bc76186/src/extensions/replay/sessionrecording-utils.ts#L14

**Comment by andrei-zanouski** [comment]
@pauldambra Hi, but we are getting this error in realtime on frontend side 

>Array.prototype.at is not available

Yes, it's true. Most of the bugs are related to Safari 15.3. 

`.at` got [full support in  Safari 15.4](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility). 

How about using `array[index]` instead of `.at` for support older version of Safari?

**Comment by pauldambra** [comment]
Ah, what a pain... we have a linter to protect us from breaking compatability but it's purposefully misconfigured at the moment or our IE11 tests freeze 🫠 

Will take a look

**Comment by pauldambra** [comment]
issue auto-closed by mention @andrei-zanouski but feel free to let us know if this doesn't resolve it here! - it'll be out in 1.188.1 shortly

thanks for working through it with me!

**Comment by pauldambra** [comment]
also @aleksandr-shevchenko-0

**Comment by andrei-zanouski** [comment]
Thanks a lot!
