### ISSUE TITLE
TypeError: Cannot read property 'hostname' of undefined - During Next JS Static Build time

### ISSUE THREAD

**Issue by anuraagy** [PostHog/posthog-js#167]
I'm getting this below error on the statically generated pages of my Next.js application. For context, my application on Render.com and this is happening during build time.

```
Jan 4 10:20:45 AM  TypeError: Cannot read property 'hostname' of undefined
    at defaultConfig (/opt/render/project/src/app/node_modules/posthog-js/dist/module.js:4727:49)
    at PostHogLib._init (/opt/render/project/src/app/node_modules/posthog-js/dist/module.js:4887:32)
    at create_mplib (/opt/render/project/src/app/node_modules/posthog-js/dist/module.js:4793:12)
    at PostHogLib.posthog_master.init (/opt/render/project/src/app/node_modules/posthog-js/dist/module.js:6158:20)
    at buildPosthog (/opt/render/project/src/app/.next/server/pages/404.js:741:37)
    at Layout (/opt/render/project/src/app/.next/server/pages/404.js:822:58)
    at d (/opt/render/project/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/opt/render/project/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/opt/render/project/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/opt/render/project/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44
```

**Comment by macobo** [comment]
Are you calling `posthog.init` in next.js during server-side render? At the moment the library assumes it gets initialized within a browser.

**Comment by paolodamico** [comment]
Relevant context, https://posthogusers.slack.com/archives/CT7HXDEG3/p1608884179362300. We might've changed something in the way we load the library too because rolling back seems to work.

**Comment by anuraagy** [comment]
@macobo  Yep, you're right! It works now that I make sure it only runs on the client side. Thank you! Closing the issue now.

**Comment by paolodamico** [comment]
Thanks for detailing your solution @anuraagy!
