### ISSUE TITLE
call without distinctId (mandatory) causes ~10 second timeout awaiting client.shtdown()

### ISSUE THREAD

**Issue by tompscanlan** [PostHog/posthog-js#2145]
## Bug description
In a minimal node http handler I'm trying to use posthog to capture an event.  I'm seeing a ~10 second timeout when waiting on the call to shutdown(). At that time I get the error:

 ERROR  Error while shutting down PostHog HTTP error while fetching PostHog: 400

  at retriable (node_modules/posthog-core/src/index.ts:652:17)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at retriable (node_modules/posthog-core/src/utils.ts:27:19)
  at PostHog.fetchWithRetry (node_modules/posthog-core/src/index.ts:635:12)
  at PostHog._flush (node_modules/posthog-core/src/index.ts:605:7)
  
## How to reproduce

This is a Nuxt project backend running in node 20.

```import { PostHog } from "posthog-node";

export default defineEventHandler(async (event) => {
  let posthogClient = null;
  try {
    posthogClient = new PostHog("XXXXX", {
      host: "https://us.i.posthog.com",
    });
    posthogClient.on("error", (err) => {
        console.error("PostHog had an error!", err);
    });
    posthogClient.debug();
    posthogClient.capture({
      distinct_id: "test",
      event: "Test",
    });
  
  } catch (error) {
    console.error("Error initializing PostHog:", error);
  } finally {
  await posthogClient.shutdown();
}
});

```

## Additional context
I'm not to posthog, and a hack front end person, I'm probably doing something silly.  I'm getting front end events through just fine using the same api key, but none of my backend events show up, and get a 400 instead.

**Comment by marandaneto** [comment]
Missing distinctId now generates an anonymous UUID and avoids the invalid 400
