### ISSUE TITLE
this.get_config is not a function

### ISSUE THREAD

**Issue by alan-cooney** [PostHog/posthog-js#342]
Hi,

We're getting the following error logs from Sentry:

```
TypeError: this.get_config is not a function
  at unload(./node_modules/posthog-js/dist/es.js:5402:22)
  at apply(./node_modules/posthog-js/dist/es.js:5924:20)
  at r(./node_modules/@sentry/browser/esm/helpers.js:73:23)
```

```javascript
          try {
            window.navigator.sendBeacon(url, encodePostData(data, _objectSpread2(_objectSpread2({}, options), {}, {
              sendBeacon: true
            })));
          } catch (e) {
            if (this.get_config('debug')) { // The error is occurring here
              console.error(e);
            }
          }
        }
      } catch (err) {
```

It looks like this occurs when sendBeacon fails and is retrying (the browser automatically does this), and then the reference to contextual `this` is lost.

**Comment by NickPuljic** [comment]
We are also seeing this
